In [1]:
import pandas as pd, numpy as np

In [79]:
grant_df = pd.read_csv('Grant.csv')
grant_df.columns = grant_df.iloc[0]
grant_df = grant_df[1:].drop(['Rank','Grant ID', 'Grant Number','Title','Abstract','Funding Amount','Currency',
                             'Source Linkout','Dimensions URL','RCDC Categories','HRCS HC Categories',
                              'HRCS RAC Categories','ICRP Cancer Types','ICRP CSO Categories','Start Date',
                              'End Date','Research Organization - original','Research Organization - standardized',
                             'City of Research organization','State of Research organization',
                              'Country of Research organization','Researchers',
                             'GRID ID','Resulting publications'],axis = 1)
grant_df

,Title translated,Abstract translated,Funding Amount in USD,Start Year,End Year,Funder,Funder Group,Funder Country,FOR (ANZSRC) Categories,Units of Assessment,Sustainable Development Goals
1,CAREER: Heat Semigroups and Strichartz Estimat...,This award is funded in whole or in part under...,424657,2022,2027,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,0102 Applied Mathematics; 01 Mathematical Scie...,B10 Mathematical Sciences,NaN
2,SCC-IRG Track1: ADVANCED LEARNING FOR ENERGY R...,This NSF S&CC project aims to predict the Stat...,1498793,2022,2026,Directorate for Engineering,NSF - National Science Foundation,United States,1117 Public Health and Health Services; 11 Med...,B11 Computer Science and Informatics,13 Climate Action
3,CAREER: Dislocation-level Understanding of She...,PART 1: NON-TECHNICAL SUMMARY Magnesium (Mg) i...,464494,2022,2027,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,0912 Materials Engineering; 09 Engineering,B12 Engineering,NaN
4,"CAREER: Past, Present, and Future of the Peatl...",Tropical ecosystems are subject to some of the...,816374,2022,2027,Directorate for Biological Sciences,NSF - National Science Foundation,United States,0602 Ecology; 0502 Environmental Science and M...,C14 Geography and Environmental Studies,13 Climate Action
5,CAREER: Integrating river hydrology across sca...,Rivers are natural hotspots for greenhouse gas...,535242,2022,2027,Directorate for Geosciences,NSF - National Science Foundation,United States,0406 Physical Geography and Environmental Geos...,C14 Geography and Environmental Studies,13 Climate Action
...,...,...,...,...,...,...,...,...,...,...,...
4996,Mathematical Sciences: Algebraic Cycles on Sur...,NaN,31000,1985,1987,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,NaN,NaN,NaN
4997,Purchase of a High Resolution Fourier Transfor...,NaN,175000,1985,1986,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,NaN,NaN,NaN
4998,Graduate Research Fellowships Support Grant,NaN,46500,1985,1990,Directorate for Education & Human Resources,NSF - National Science Foundation,United States,NaN,NaN,NaN
4999,Warm Core Ring Interdisciplinary Synthesis Pro...,NaN,37157,1985,1987,Directorate for Geosciences,NSF - National Science Foundation,United States,NaN,NaN,NaN
5000,A History of High-Pressure Coal Hydrogenation ...,NaN,9000,1985,1986,Directorate for Biological Sciences,NSF - National Science Foundation,United States,NaN,NaN,NaN

In [80]:
grant_df['Funding per year'] = 10**(-5)*grant_df['Funding Amount in USD'].astype('float')/(1+grant_df['End Year'].astype('float') - grant_df['Start Year'].astype('float'))
grant_df = grant_df.drop(['Funding Amount in USD'], axis = 1)

In [81]:
grant_df = grant_df.dropna(subset = ['Funding per year'])
grant_df

,Title translated,Abstract translated,Start Year,End Year,Funder,Funder Group,Funder Country,FOR (ANZSRC) Categories,Units of Assessment,Sustainable Development Goals,Funding per year
1,CAREER: Heat Semigroups and Strichartz Estimat...,This award is funded in whole or in part under...,2022,2027,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,0102 Applied Mathematics; 01 Mathematical Scie...,B10 Mathematical Sciences,NaN,0.707762
2,SCC-IRG Track1: ADVANCED LEARNING FOR ENERGY R...,This NSF S&CC project aims to predict the Stat...,2022,2026,Directorate for Engineering,NSF - National Science Foundation,United States,1117 Public Health and Health Services; 11 Med...,B11 Computer Science and Informatics,13 Climate Action,2.997586
3,CAREER: Dislocation-level Understanding of She...,PART 1: NON-TECHNICAL SUMMARY Magnesium (Mg) i...,2022,2027,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,0912 Materials Engineering; 09 Engineering,B12 Engineering,NaN,0.774157
4,"CAREER: Past, Present, and Future of the Peatl...",Tropical ecosystems are subject to some of the...,2022,2027,Directorate for Biological Sciences,NSF - National Science Foundation,United States,0602 Ecology; 0502 Environmental Science and M...,C14 Geography and Environmental Studies,13 Climate Action,1.360623
5,CAREER: Integrating river hydrology across sca...,Rivers are natural hotspots for greenhouse gas...,2022,2027,Directorate for Geosciences,NSF - National Science Foundation,United States,0406 Physical Geography and Environmental Geos...,C14 Geography and Environmental Studies,13 Climate Action,0.892070
...,...,...,...,...,...,...,...,...,...,...,...
4996,Mathematical Sciences: Algebraic Cycles on Sur...,NaN,1985,1987,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,NaN,NaN,NaN,0.103333
4997,Purchase of a High Resolution Fourier Transfor...,NaN,1985,1986,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,NaN,NaN,NaN,0.875000
4998,Graduate Research Fellowships Support Grant,NaN,1985,1990,Directorate for Education & Human Resources,NSF - National Science Foundation,United States,NaN,NaN,NaN,0.077500
4999,Warm Core Ring Interdisciplinary Synthesis Pro...,NaN,1985,1987,Directorate for Geosciences,NSF - National Science Foundation,United States,NaN,NaN,NaN,0.123857
5000,A History of High-Pressure Coal Hydrogenation ...,NaN,1985,1986,Directorate for Biological Sciences,NSF - National Science Foundation,United States,NaN,NaN,NaN,0.045000

In [82]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
grant_df['FOR (ANZSRC) Categories'] = grant_df['FOR (ANZSRC) Categories'].fillna('')

In [83]:
index_df = grant_df.copy()
index_df.shape

(4925, 11)

In [84]:
tmp_df = grant_df['FOR (ANZSRC) Categories'].apply(lambda x: x.split(";"))
array_out = mlb.fit_transform(tmp_df)
df_out = pd.DataFrame(data=array_out, columns=mlb.classes_, index = grant_df.index)
df_out.columns = df_out.columns.str.replace("'"," ")
df_out

,,01 Mathematical Sciences,0101 Pure Mathematics,0102 Applied Mathematics,0103 Numerical and Computational Mathematics,0104 Statistics,02 Physical Sciences,0201 Astronomical and Space Sciences,"0202 Atomic, Molecular, Nuclear, Particle and Plasma Physics",0204 Condensed Matter Physics,...,1701 Psychology,1702 Cognitive Sciences,1801 Law,2002 Cultural Studies,2004 Linguistics,2005 Literary Studies,2101 Archaeology,2103 Historical Studies,2203 Philosophy,2204 Religion and Religious Studies
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4998,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5000,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [85]:
grant_df = pd.concat([grant_df, df_out],axis =1).drop(['FOR (ANZSRC) Categories'],axis =1 )

,Title translated,Abstract translated,Start Year,End Year,Funder,Funder Group,Funder Country,Units of Assessment,Sustainable Development Goals,Funding per year,...,1701 Psychology,1702 Cognitive Sciences,1801 Law,2002 Cultural Studies,2004 Linguistics,2005 Literary Studies,2101 Archaeology,2103 Historical Studies,2203 Philosophy,2204 Religion and Religious Studies
2,SCC-IRG Track1: ADVANCED LEARNING FOR ENERGY R...,This NSF S&CC project aims to predict the Stat...,2022,2026,Directorate for Engineering,NSF - National Science Foundation,United States,B11 Computer Science and Informatics,13 Climate Action,2.997586,...,0,0,0,0,0,0,0,0,0,0
3,CAREER: Dislocation-level Understanding of She...,PART 1: NON-TECHNICAL SUMMARY Magnesium (Mg) i...,2022,2027,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,B12 Engineering,NaN,0.774157,...,0,0,0,0,0,0,0,0,0,0
4,"CAREER: Past, Present, and Future of the Peatl...",Tropical ecosystems are subject to some of the...,2022,2027,Directorate for Biological Sciences,NSF - National Science Foundation,United States,C14 Geography and Environmental Studies,13 Climate Action,1.360623,...,0,0,0,0,0,0,0,0,0,0
5,CAREER: Integrating river hydrology across sca...,Rivers are natural hotspots for greenhouse gas...,2022,2027,Directorate for Geosciences,NSF - National Science Foundation,United States,C14 Geography and Environmental Studies,13 Climate Action,0.892070,...,0,0,0,0,0,0,0,0,0,0
6,REU Site: Undergraduate Research in the Mathem...,This award is funded in whole or in part under...,2022,2025,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,B10 Mathematical Sciences,NaN,0.971390,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,Mathematical Sciences: Algebraic Cycles on Sur...,NaN,1985,1987,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,NaN,NaN,0.103333,...,0,0,0,0,0,0,0,0,0,0
4997,Purchase of a High Resolution Fourier Transfor...,NaN,1985,1986,Directorate for Mathematical & Physical Sciences,NSF - National Science Foundation,United States,NaN,NaN,0.875000,...,0,0,0,0,0,0,0,0,0,0
4998,Graduate Research Fellowships Support Grant,NaN,1985,1990,Directorate for Education & Human Resources,NSF - National Science Foundation,United States,NaN,NaN,0.077500,...,0,0,0,0,0,0,0,0,0,0
4999,Warm Core Ring Interdisciplinary Synthesis Pro...,NaN,1985,1987,Directorate for Geosciences,NSF - National Science Foundation,United States,NaN,NaN,0.123857,...,0,0,0,0,0,0,0,0,0,0
5000,A History of High-Pressure Coal Hydrogenation ...,NaN,1985,1986,Directorate for Biological Sciences,NSF - National Science Foundation,United States,NaN,NaN,0.045000,...,0,0,0,0,0,0,0,0,0,0

In [86]:
grant_df =  grant_df.drop(['Funder','Units of Assessment'],axis =1)
grant_df

,Title translated,Abstract translated,Start Year,End Year,Funder Group,Funder Country,Sustainable Development Goals,Funding per year,,01 Mathematical Sciences,...,1701 Psychology,1702 Cognitive Sciences,1801 Law,2002 Cultural Studies,2004 Linguistics,2005 Literary Studies,2101 Archaeology,2103 Historical Studies,2203 Philosophy,2204 Religion and Religious Studies
1,CAREER: Heat Semigroups and Strichartz Estimat...,This award is funded in whole or in part under...,2022,2027,NSF - National Science Foundation,United States,NaN,0.707762,0,1,...,0,0,0,0,0,0,0,0,0,0
2,SCC-IRG Track1: ADVANCED LEARNING FOR ENERGY R...,This NSF S&CC project aims to predict the Stat...,2022,2026,NSF - National Science Foundation,United States,13 Climate Action,2.997586,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CAREER: Dislocation-level Understanding of She...,PART 1: NON-TECHNICAL SUMMARY Magnesium (Mg) i...,2022,2027,NSF - National Science Foundation,United States,NaN,0.774157,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"CAREER: Past, Present, and Future of the Peatl...",Tropical ecosystems are subject to some of the...,2022,2027,NSF - National Science Foundation,United States,13 Climate Action,1.360623,0,0,...,0,0,0,0,0,0,0,0,0,0
5,CAREER: Integrating river hydrology across sca...,Rivers are natural hotspots for greenhouse gas...,2022,2027,NSF - National Science Foundation,United States,13 Climate Action,0.892070,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,Mathematical Sciences: Algebraic Cycles on Sur...,NaN,1985,1987,NSF - National Science Foundation,United States,NaN,0.103333,1,0,...,0,0,0,0,0,0,0,0,0,0
4997,Purchase of a High Resolution Fourier Transfor...,NaN,1985,1986,NSF - National Science Foundation,United States,NaN,0.875000,1,0,...,0,0,0,0,0,0,0,0,0,0
4998,Graduate Research Fellowships Support Grant,NaN,1985,1990,NSF - National Science Foundation,United States,NaN,0.077500,1,0,...,0,0,0,0,0,0,0,0,0,0
4999,Warm Core Ring Interdisciplinary Synthesis Pro...,NaN,1985,1987,NSF - National Science Foundation,United States,NaN,0.123857,1,0,...,0,0,0,0,0,0,0,0,0,0
5000,A History of High-Pressure Coal Hydrogenation ...,NaN,1985,1986,NSF - National Science Foundation,United States,NaN,0.045000,1,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
temp_df2 = pd.get_dummies(grant_df[['Funder Group','Funder Country']])
grant_df = pd.concat([grant_df, temp_df2],axis =1).set_index(index_df.index)
grant_df

,Title translated,Abstract translated,Start Year,End Year,Funder Group,Funder Country,Sustainable Development Goals,Funding per year,,01 Mathematical Sciences,...,Funder Country_Australia,Funder Country_Belgium,Funder Country_Canada,Funder Country_Germany,Funder Country_Japan,Funder Country_Portugal,Funder Country_Qatar,Funder Country_Switzerland,Funder Country_United Kingdom,Funder Country_United States
1,CAREER: Heat Semigroups and Strichartz Estimat...,This award is funded in whole or in part under...,2022,2027,NSF - National Science Foundation,United States,NaN,0.707762,0,1,...,0,0,0,0,0,0,0,0,0,1
2,SCC-IRG Track1: ADVANCED LEARNING FOR ENERGY R...,This NSF S&CC project aims to predict the Stat...,2022,2026,NSF - National Science Foundation,United States,13 Climate Action,2.997586,0,0,...,0,0,0,0,0,0,0,0,0,1
3,CAREER: Dislocation-level Understanding of She...,PART 1: NON-TECHNICAL SUMMARY Magnesium (Mg) i...,2022,2027,NSF - National Science Foundation,United States,NaN,0.774157,0,0,...,0,0,0,0,0,0,0,0,0,1
4,"CAREER: Past, Present, and Future of the Peatl...",Tropical ecosystems are subject to some of the...,2022,2027,NSF - National Science Foundation,United States,13 Climate Action,1.360623,0,0,...,0,0,0,0,0,0,0,0,0,1
5,CAREER: Integrating river hydrology across sca...,Rivers are natural hotspots for greenhouse gas...,2022,2027,NSF - National Science Foundation,United States,13 Climate Action,0.892070,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,Mathematical Sciences: Algebraic Cycles on Sur...,NaN,1985,1987,NSF - National Science Foundation,United States,NaN,0.103333,1,0,...,0,0,0,0,0,0,0,0,0,1
4997,Purchase of a High Resolution Fourier Transfor...,NaN,1985,1986,NSF - National Science Foundation,United States,NaN,0.875000,1,0,...,0,0,0,0,0,0,0,0,0,1
4998,Graduate Research Fellowships Support Grant,NaN,1985,1990,NSF - National Science Foundation,United States,NaN,0.077500,1,0,...,0,0,0,0,0,0,0,0,0,1
4999,Warm Core Ring Interdisciplinary Synthesis Pro...,NaN,1985,1987,NSF - National Science Foundation,United States,NaN,0.123857,1,0,...,0,0,0,0,0,0,0,0,0,1
5000,A History of High-Pressure Coal Hydrogenation ...,NaN,1985,1986,NSF - National Science Foundation,United States,NaN,0.045000,1,0,...,0,0,0,0,0,0,0,0,0,1

In [88]:
grant_TDA = grant_df.drop(['Title translated','Abstract translated',
                          'Start Year','Funder Group','Funder Country',
                          'Sustainable Development Goals'],axis =1)

In [68]:
grant_TDA['End Year'] = grant_TDA['End Year'].astype(float)
grant_TDA

,End Year,Funding per year,01 Mathematical Sciences,0101 Pure Mathematics,0102 Applied Mathematics,0103 Numerical and Computational Mathematics,0104 Statistics,02 Physical Sciences,0201 Astronomical and Space Sciences,"0202 Atomic, Molecular, Nuclear, Particle and Plasma Physics",...,Funder Country_Australia,Funder Country_Belgium,Funder Country_Canada,Funder Country_Germany,Funder Country_Japan,Funder Country_Portugal,Funder Country_Qatar,Funder Country_Switzerland,Funder Country_United Kingdom,Funder Country_United States
1,2027.0,0.707762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
2,2026.0,2.997586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
3,2027.0,0.774157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
4,2027.0,1.360623,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
5,2027.0,0.892070,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,1987.0,0.103333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
4997,1986.0,0.875000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
4998,1990.0,0.077500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
4999,1987.0,0.123857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
5000,1986.0,0.045000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [91]:
grant_TDA = grant_TDA.drop([''],axis=1).fillna(0)
grant_TDA

,End Year,Funding per year,01 Mathematical Sciences,0101 Pure Mathematics,0102 Applied Mathematics,0103 Numerical and Computational Mathematics,0104 Statistics,02 Physical Sciences,0201 Astronomical and Space Sciences,"0202 Atomic, Molecular, Nuclear, Particle and Plasma Physics",...,Funder Country_Australia,Funder Country_Belgium,Funder Country_Canada,Funder Country_Germany,Funder Country_Japan,Funder Country_Portugal,Funder Country_Qatar,Funder Country_Switzerland,Funder Country_United Kingdom,Funder Country_United States
1,2027,0.707762,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2026,2.997586,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,2027,0.774157,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2027,1.360623,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,2027,0.892070,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,1987,0.103333,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4997,1986,0.875000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4998,1990,0.077500,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4999,1987,0.123857,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5000,1986,0.045000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
grant_df['Math'] = grant_df[' 01 Mathematical Sciences'] + grant_df['0101 Pure Mathematics']+grant_df['0102 Applied Mathematics']+grant_df['0103 Numerical and Computational Mathematics']+grant_df['0104 Statistics']
grant_df['Physics'] = grant_df[' 02 Physical Sciences'] + grant_df['0201 Astronomical and Space Sciences']+grant_df['0202 Atomic, Molecular, Nuclear, Particle and Plasma Physics']+grant_df['0204 Condensed Matter Physics']+grant_df['0205 Optical Physics']+grant_df['0206 Quantum Physics']+grant_df['0299 Other Physical Sciences']
grant_df['Chemistry'] = grant_df[' 03 Chemical Sciences'] + grant_df['0301 Analytical Chemistry']+grant_df['0302 Inorganic Chemistry']+grant_df['0303 Macromolecular and Materials Chemistry']+grant_df['0304 Medicinal and Biomolecular Chemistry']+grant_df['0305 Organic Chemistry'] +grant_df['0306 Physical Chemistry (incl. Structural)']+grant_df['0307 Theoretical and Computational Chemistry']
grant_df['Earth Science'] = grant_df[' 04 Earth Sciences']+grant_df['0401 Atmospheric Sciences']+grant_df['0402 Geochemistry']+grant_df['0403 Geology']+grant_df['0404 Geophysics']+grant_df['0405 Oceanography']+grant_df['0406 Physical Geography and Environmental Geoscience']
grant_df['Environmental'] = grant_df[' 05 Environmental Sciences'] +grant_df['0501 Ecological Applications']+grant_df['0502 Environmental Science and Management']+grant_df['0503 Soil Sciences']
grant_df['Biology'] = grant_df[' 06 Biological Sciences']+grant_df['0601 Biochemistry and Cell Biology']+grant_df['0602 Ecology']+grant_df['0603 Evolutionary Biology']+grant_df['0604 Genetics']+grant_df['0605 Microbiology']+grant_df['0606 Physiology']+grant_df['0607 Plant Biology']+grant_df['0608 Zoology']
grant_df[''] = grant_df[' 07 Agricultural and Veterinary Sciences']